<<<<<<< HEAD
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
=======
theme: jekyll-theme-cayman
>>>>>>> a97b67efb907237cab52647f04d4354ca3d6e5e5
